### ISSUE TITLE
Lotto link should be made more obvious, spawn new tab

### ISSUE THREAD

**Issue by docsane** [Bronystate/brstv3#26]
Current lotto link in news text is hard to find, not immediately obvious. Suggest making the link a permanent, obvious feature of the page UI. Also, current link will take you from Bronystate to the survey page. This will kick you out of chat and video stream unless you manually tell it to open in a new tab. Can link be made to automatically open a new tab and keep main Bronystate window as-is?

**Comment by shizuka** [comment]
Per #27, it's not feasible to have Javascript crawl every page to set external links to open in `_blank`, and it's not possible at all with pure CSS.

![Example of extlink](http://i.imgur.com/cKizikv.png)

All external links are already clearly marked with an icon. Users must understand that by clicking a link, they are pointing their browser at a new page, and so connections from one page will disappear. Iris warns you about leaving a page if you are connected anyway. Users can learn to use the middle mouse button to open new tabs. It's how the modern web works.

Lottery links will always be in the current lottery post. Their prominence is a matter of standardizing the format we post lottery winners in, which will take a bit of time. An alternative would be to put the latest lottery in the sidebar, but that leads to duplication of effort on our part, and doesn't have the built in fail state of not showing when the post is no longer relevant (per e304ab9509977468804c5c8cfc183593334ef730).

Issue may be reopened in the future if users submit requests for it. Until then, wontfix.
