### ISSUE TITLE
Update About Us page

### ISSUE THREAD

**Issue by shizuka** [Bronystate/brstv3#31]
http://www.bronystate.net/about

Ornaments are a cutie mark, foreground color (color of the mark) and background color (color of the circle). Don't need exact, just need _something_ to go on, can easily make designs myself.

Info block is location, favorite pony, favorite movie. Have a look at the page for examples.

Need updates from the following staff:
- **Eulshy**
  - [ ] Ornament details
  - [ ] Info block
- @Fengor45 
  - [ ] Ornament details
  - [ ] Info block
- @GabeMoist 
  - [ ] Ornament details
- **Krazy**
  - [ ] Ornament details
- @ariscop (Phase)
  - [ ] Ornament details
  - [ ] Info block

Info block updates should be made to https://github.com/Bronystate/brstv3/blob/master/_data/staff-list.yml

Send me ornament details and I'll make it up

**Comment by CriticKitten** [comment]
Pages have been updated for these staff, at least the ones still with us, so marking this close.
