### ISSUE TITLE
Your email system is fucked

### ISSUE THREAD

**Issue by fuckinshit** [Bronystate/brstv3#37]
I unsubsribed to receiving emails from the site months ago since I don't visit anymore. But, every so often for some dumbass reason, I still get them randomly. I had to block the site's address entirely to stop the spam. Now all of a sudden I get THIS. This might be spam from a completely different source but still wtf.
![fuck](https://cloud.githubusercontent.com/assets/16567001/12130721/b5482a1c-b3c1-11e5-9307-fe46e5115999.PNG)

**Comment by ariscop** [comment]
Bizzare, if you jump on irc and send one of the mods your email we can manually remove itm but there's not much we can do about a third party sending you stuff

**Comment by Fengor45** [comment]
If you check the e-mail address it was sent from you'll see that it's not from us. The only communication we send out comes from either bronystate@gmail.com or newsletter@bronystate.net; the newsletter was discontinued some time ago.

We're sorry you got spam from someone pretending to be us, (And equally sorry that our previously terrible manual method of managing the newsletter sendouts meant you continued to receive them after unsubscribing.) but there's not a whole lot we can do unfortunately.

If you have anymore problems in the future, then please send a message to bronystate@gmail.com; which gets checked more often than GitHub.

**Comment by shizuka** [comment]
Problem is with the originating address, not Bronystate.

Report the actual spammer, not us. Thanks.
